Repository jlusiardi/homekit_python, pull requests merged in 2019-01, with the labels that each got.

#79 Fix 75 datamigration
  homekit/controller/controller.py
  tests/controller_test.py
Labels: bugfix

#82 Add tests for BLE implementation of controller
  homekit/controller/ble_impl/__init__.py
  homekit/controller/ble_impl/device.py
  homekit/controller/ble_impl/discovery.py
  homekit/controller/ble_impl/gatt.py
  homekit/controller/ble_impl/manufacturer_data.py
  homekit/controller/controller.py
  homekit/discover_ble.py
  homekit/exceptions.py
  homekit/model/characteristics/abstract_characteristic.py
  homekit/model/characteristics/characteristic_formats.py
  requirements.txt
  staging/gatt/SOURCE.md
  staging/gatt/__init__.py
  staging/gatt/errors.py
  staging/gatt/gatt.py
  staging/gatt/gatt_linux.py
  staging/gatt/gatt_stubs.py
  staging/hap_char_sig_read.py
  staging/hap_pair.py
  staging/hap_pair_verify.py
  staging/hap_pair_verify_read_name.py
  staging/hap_read_pairingfeatures.py
  staging/homekit_discovery.py
  staging/tools.py
  tests/__init__.py
  tests/ble_controller_test.py
  tests/controller_test.py
Labels: BLE Transport

#94 Avoid gmpy2 dependency
  .travis.yml
  README.md
  homekit/accessoryserver.py
  homekit/crypto/srp.py
  requirements.txt
  setup.py
Labels: Installation

#95 Avoid py25519 dependency with cryptography.
  homekit/accessoryserver.py
  homekit/protocol/__init__.py
  requirements.txt
  setup.py
Labels: Installation

#91 Automatically close session on network failure
  homekit/controller.py
  homekit/exceptions.py
  homekit/http_impl/secure_http.py
Labels: IP Transport, bug
